# Generated by Django 4.1 on 2023-04-15 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_teacher_class_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teacher_id',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject_id',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.subject'),
        ),
    ]
